'use client'
import Footer from "@/components/Footer";
// import Features from "@/components/LandingPage/Features";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { CardDemo } from "@/components/ui/CardDemo";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="bg-black-800">
      <Navbar />
      <main className="MainContainer my-5 p-5 items-center justify-center sm:p-20 flex md:flex-row flex-col-reverse">
        <div className="ContentContainer p-5 md:p-0 w-full md:w-1/2 flex justify-center flex-col">
          {/* <p className="text-center md:text-left text-gray-400">AI makes content fast and easy</p> */}
          <h1 className="text-center text-3xl sm:text-5xl md:text-7xl font-bold py-5 text-gray-300">
            Learn Smarter with <span className="text-gradient">AI-Driven</span> Guidance
          </h1>
          <p className="text-center text-gray-400">
            Discover structured learning paths tailored to your skills, interests, and ambitions — all built in seconds by AI.
          </p>

          <Link className="flex items-center justify-center" href='/#features-section'>
            <Button className="h-12 bg-blue-600 hover:bg-blue-500 text-lg font-semibold my-5">Explore Features</Button>
          </Link>
        </div>
      </main>

      <div className="ImageContainer w-1/2 my-auto mx-auto">
        <Image className="mx-auto my-auto" width={650} height={650} src="timeline.svg" alt="Roadmap image" />
      </div>

      <div className="flex items-center flex-col text-center mx-2">
        <h1 className="text-3xl sm:text-4xl md:text-5xl py-5 my-10 mx-auto w-full md:w-9/12 font-bold text-gray-300">Take the Leap and Dive into an Exceptional Experience on Our Website!</h1>

      </div>

      {/* <Features /> */}

      <div id='features-section' className='flex flex-col items-center justify-center my-10'>
        <div className="flex flex-wrap justify-center md:justify-evenly px-5 md:px-20 lg:px-40 py-10 gap-5">
          {featuresArr.map((item, index) => (
            <div key={index} className="w-full sm:w-auto mx-5">
              <CardDemo
                title={item.title}
                heading={item.heading}
                avatar={item.avatar}
                content={item.content}
              />
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}


export const featuresArr = [
  {
    title: "AI-Powered Learning",
    heading: "Personalized Roadmaps",
    avatar: "feature1.png",
    content: "Experience customized learning paths generated by AI, tailored to your preferences. Our platform adapts to your unique learning journey."
  },
  {
    title: "Progress Tracking",
    heading: "Visual Progress",
    avatar: "feature2.png",
    content: "Track your learning journey with interactive visualizations. Watch your progress grow with our beautiful roadmap view and completion indicators."
  },
  {
    title: "Resource Integration",
    heading: "Curated Resources",
    avatar: "feature1.png",
    content: "Access hand-picked learning resources for each topic. Every step of your roadmap comes with quality documentation link."
  },
  {
    title: "Timeline View",
    heading: "Structured Learning",
    avatar: "feature2.png",
    content: "Navigate your learning path with our intuitive timeline view. Break down complex topics into manageable subtopics and track completion."
  },
  {
    title: "Task Management",
    heading: "Stay Organized",
    avatar: "feature1.png",
    content: "Manage your learning tasks effectively. Mark topics as complete, track duration estimates, and maintain steady progress towards your goals."
  },
  {
    title: "Daily progress report",
    heading: "Daily progress report",
    avatar: "feature2.png",
    content: "Recieve your progress report on daily basis via email, to keep you motivated and on track with your learning goals."
  }
];